In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [74]:
data = pd.read_excel("C:/Users/Prince '/OneDrive/DA_Project/Ecommerce_Sales_Data_2024_2025.xlsx")
print(data)

      Order ID Order Date  Year Month  Day     Customer Name Region  \
0        10147 2024-01-01  2024   Jan    1  Nayantara Kalita   West
1        10941 2024-01-01  2024   Jan    1     Indranil Char  South
2        11271 2024-01-01  2024   Jan    1      Jayant Dugar  North
3        11299 2024-01-01  2024   Jan    1        Ela Wadhwa  South
4        12716 2024-01-01  2024   Jan    1      Sana Trivedi  North
...        ...        ...   ...   ...  ...               ...    ...
4997     10366 2025-10-03  2025   Oct    3        Rasha Sule   West
4998     11524 2025-10-03  2025   Oct    3      Pranay Saraf   West
4999     12505 2025-10-03  2025   Oct    3        Heer Banik  North
5000     11524 2025-10-03  2025   Oct    3      Pranay Saraf   West
5001     12505 2025-10-03  2025   Oct    3        Heer Banik  North

                    City     Category   Sub-Category             Product Name  \
0              Ahmedabad  Electronics     Smartwatch           Smartwatch Eum
1             Coimbatore       Sports    Cricket Bat   Cricket Bat Distinctio
2                Lucknow    Furniture          Table         Table Laudantium
3     Thiruvananthapuram        Books         Comics           Comics Nostrum
4                  Delhi         Toys  Action Figure     Action Figure Libero
...                  ...          ...            ...                      ...
4997               Surat         Toys  Action Figure  Action Figure Veritatis
4998              Mumbai       Beauty     Foundation     Foundation Veritatis
4999              Jaipur    Groceries            Oil          Oil Repellendus
5000              Mumbai       Beauty     Foundation     Foundation Veritatis
5001              Jaipur    Groceries            Oil          Oil Repellendus

      Quantity  Unit  Price  Total Sales Profit %  Profit Amount Payment Mode
0            2         9607        19214      10%        1921.40  Net Banking
1            5         9648        48240      20%        9648.00  Net Banking
2            5         7213        36065      20%        7213.00   Debit Card
3            2         7000        14000      10%        1400.00  Net Banking
4            5         8800        44000      20%        8800.00   Debit Card
...        ...          ...          ...      ...            ...          ...
4997         1         9427         9427       5%         471.35          UPI
4998         5         8114        40570      20%        8114.00  Net Banking
4999         3         8112        24336      15%        3650.40  Net Banking
5000         5         8114        40570      20%        8114.00  Net Banking
5001         3         8112        24336      15%        3650.40  Net Banking

[5002 rows x 17 columns]

In [38]:
data.head()
# data.tail()

,Order ID,Order Date,Year,Month,Day,Customer Name,Region,City,Category,Sub-Category,Product Name,Quantity,Unit Price,Total Sales,Profit %,Profit Amount,Payment Mode
0,10147,2024-01-01,2024,Jan,1,Nayantara Kalita,West,Ahmedabad,Electronics,Smartwatch,Smartwatch Eum,2,9607,19214,10%,1921.4,Net Banking
1,10941,2024-01-01,2024,Jan,1,Indranil Char,South,Coimbatore,Sports,Cricket Bat,Cricket Bat Distinctio,5,9648,48240,20%,9648.0,Net Banking
2,11271,2024-01-01,2024,Jan,1,Jayant Dugar,North,Lucknow,Furniture,Table,Table Laudantium,5,7213,36065,20%,7213.0,Debit Card
3,11299,2024-01-01,2024,Jan,1,Ela Wadhwa,South,Thiruvananthapuram,Books,Comics,Comics Nostrum,2,70,140,5%,7.0,Net Banking
4,12716,2024-01-01,2024,Jan,1,Sana Trivedi,North,Delhi,Toys,Action Figure,Action Figure Libero,5,88000,440000,20%,88000.0,Debit Card

In [25]:
data.shape
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       5000 non-null   int64
 1   Order Date     5000 non-null   datetime64[ns]
 2   Year           5000 non-null   int64
 3   Month          5000 non-null   object
 4   Day            5000 non-null   int64
 5   Customer Name  5000 non-null   object
 6   Region         5000 non-null   object
 7   City           5000 non-null   object
 8   Category       5000 non-null   object
 9   Sub-Category   5000 non-null   object
 10  Product Name   5000 non-null   object
 11  Quantity       5000 non-null   int64
 12  Unit  Price    5000 non-null   int64
 13  Total Sales    5000 non-null   int64
 14  Profit %       5000 non-null   object
 15  Profit Amount  5000 non-null   float64
 16  Payment Mode   5000 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(6), object(9)
memory usage: 664.2+ KB

In [43]:
data.describe()

,Order ID,Order Date,Year,Day,Quantity,Unit Price,Total Sales,Profit Amount
count,5000.000000,5000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000
mean,12500.500000,2024-11-13 18:48:40.320000,2024.373400,15.710400,2.99280,8118.152800,24271.239600,3956.102790
min,10001.000000,2024-01-01 00:00:00,2024.000000,1.000000,1.00000,222.000000,222.000000,11.100000
25%,11250.750000,2024-07-01 00:00:00,2024.000000,8.000000,2.00000,7555.000000,14152.000000,1415.200000
50%,12500.500000,2024-11-15 00:00:00,2024.000000,16.000000,3.00000,8387.000000,23718.000000,3557.700000
75%,13750.250000,2025-03-30 00:00:00,2025.000000,23.000000,4.00000,9235.000000,35524.000000,7104.800000
max,15000.000000,2025-10-03 00:00:00,2025.000000,31.000000,5.00000,10000.000000,49975.000000,9995.000000
std,1443.520003,NaN,0.483755,8.806909,1.41278,1706.591576,12761.414512,3081.388116

In [45]:
data.dtypes

Order ID                  int64
Order Date       datetime64[ns]
Year                      int64
Month                    object
Day                       int64
Customer Name            object
Region                   object
City                     object
Category                 object
Sub-Category             object
Product Name             object
Quantity                  int64
Unit  Price               int64
Total Sales               int64
Profit %                 object
Profit Amount           float64
Payment Mode             object
dtype: object

In [47]:
data.isnull().sum()

Order ID         0
Order Date       0
Year             0
Month            0
Day              0
Customer Name    0
Region           0
City             0
Category         0
Sub-Category     0
Product Name     0
Quantity         0
Unit  Price      0
Total Sales      0
Profit %         0
Profit Amount    0
Payment Mode     0
dtype: int64

In [80]:
data.duplicated().sum()

0

In [79]:
data = data.drop_duplicates()

In [89]:
data['Payment Mode'].unique()

array(['Net Banking', 'Debit Card', 'COD', 'Credit Card', 'UPI'],
      dtype=object)

In [94]:
data.nunique()

Order ID         5000
Order Date        642
Year                2
Month              12
Day                31
Customer Name    4844
Region              4
City               20
Category           10
Sub-Category       50
Product Name     3835
Quantity            5
Unit  Price      2364
Total Sales      4072
Profit %            4
Profit Amount    4072
Payment Mode        5
Full name          20
dtype: int64

In [98]:
data['Payment Mode'].value_counts()

Payment Mode
Net Banking    1010
COD            1005
Debit Card     1003
Credit Card     994
UPI             988
Name: count, dtype: int64

In [101]:
data[data['Payment Mode']=='COD']

,Order ID,Order Date,Year,Month,Day,Customer Name,Region,City,Category,Sub-Category,Product Name,Quantity,Unit Price,Total Sales,Profit %,Profit Amount,Payment Mode,Full name
6,13222,2024-01-01,2024,Jan,1,Kashvi Sekhon,East,Bhubaneswar,Groceries,Spices,Spices Eos,2,9632,19264,10%,1926.40,COD,BhubaneswarEast
9,11417,2024-01-02,2024,Jan,2,Jivika Dua,West,Pune,Beauty,Foundation,Foundation Quisquam,4,9726,38904,20%,7780.80,COD,PuneWest
19,10488,2024-01-04,2024,Jan,4,Ritvik Dara,East,Kolkata,Home Decor,Lamp,Lamp At,1,8516,8516,5%,425.80,COD,KolkataEast
28,14781,2024-01-04,2024,Jan,4,Faiyaz Sarraf,South,Chennai,Toys,Doll,Doll Enim,4,8208,32832,20%,6566.40,COD,ChennaiSouth
43,10974,2024-01-06,2024,Jan,6,Taran Chahal,West,Pune,Home Decor,Wall Art,Wall Art Dolores,2,7593,15186,10%,1518.60,COD,PuneWest
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4980,13581,2025-09-30,2025,Sep,30,Gokul Doctor,West,Surat,Groceries,Wheat,Wheat Corporis,3,8356,25068,15%,3760.20,COD,SuratWest
4985,12022,2025-10-01,2025,Oct,1,Samiha Sanghvi,West,Mumbai,Furniture,Table,Table Perferendis,2,8206,16412,10%,1641.20,COD,MumbaiWest
4987,12548,2025-10-01,2025,Oct,1,Tara Jaggi,South,Hyderabad,Books,Textbook,Textbook Veniam,1,9235,9235,5%,461.75,COD,HyderabadSouth
4993,10508,2025-10-02,2025,Oct,2,Amani Sankaran,East,Guwahati,Books,Textbook,Textbook Doloribus,4,9967,39868,20%,7973.60,COD,GuwahatiEast
4995,12701,2025-10-02,2025,Oct,2,Jayan Handa,North,Chandigarh,Beauty,Shampoo,Shampoo Enim,5,9707,48535,20%,9707.00,COD,ChandigarhNorth

In [105]:
data.loc[data['Payment Mode']=='COD',['Product Name','City','Total Sales']]

             Product Name         City  Total Sales
6              Spices Eos  Bhubaneswar        19264
9     Foundation Quisquam         Pune        38904
19                Lamp At      Kolkata         8516
28              Doll Enim      Chennai        32832
43       Wall Art Dolores         Pune        15186
...                   ...          ...          ...
4980       Wheat Corporis        Surat        25068
4985    Table Perferendis       Mumbai        16412
4987      Textbook Veniam    Hyderabad         9235
4993   Textbook Doloribus     Guwahati        39868
4995         Shampoo Enim   Chandigarh        48535

[1005 rows x 3 columns]

In [111]:
data.loc[(data.City=='Pune') & (data.Quantity>4)]

,Order ID,Order Date,Year,Month,Day,Customer Name,Region,City,Category,Sub-Category,Product Name,Quantity,Unit Price,Total Sales,Profit %,Profit Amount,Payment Mode,Full name
71,10020,2024-01-11,2024,Jan,11,Gatik Ravi,West,Pune,Books,Textbook,Textbook Inventore,5,9639,48195,20%,9639.00,Debit Card,PuneWest
99,10955,2024-01-15,2024,Jan,15,Lavanya Ahuja,West,Pune,Clothing,Kids Wear,Kids Wear Velit,5,3019,15095,10%,1509.50,Debit Card,PuneWest
229,13872,2024-02-01,2024,Feb,1,Khushi Seth,West,Pune,Sports,Yoga Mat,Yoga Mat Autem,5,9395,46975,20%,9395.00,COD,PuneWest
382,10579,2024-02-24,2024,Feb,24,Amira Kala,West,Pune,Toys,Action Figure,Action Figure Quidem,5,7349,36745,20%,7349.00,UPI,PuneWest
384,13405,2024-02-24,2024,Feb,24,Nishith Krish,West,Pune,Furniture,Sofa,Sofa Vel,5,8619,43095,20%,8619.00,Debit Card,PuneWest
414,11676,2024-02-29,2024,Feb,29,Prerak Magar,West,Pune,Toys,Board Game,Board Game Culpa,5,5874,29370,15%,4405.50,Credit Card,PuneWest
498,14773,2024-03-11,2024,Mar,11,Aarna Borde,West,Pune,Toys,RC Car,RC Car Dicta,5,7439,37195,20%,7439.00,Net Banking,PuneWest
513,10074,2024-03-14,2024,Mar,14,Vritika Gade,West,Pune,Toys,Puzzle,Puzzle Nesciunt,5,7000,35000,20%,7000.00,Credit Card,PuneWest
557,13852,2024-03-21,2024,Mar,21,Vivaan Kala,West,Pune,Furniture,Cabinet,Cabinet Dolores,5,9288,46440,20%,9288.00,COD,PuneWest
729,13971,2024-04-15,2024,Apr,15,Umang Roy,West,Pune,Furniture,Chair,Chair Harum,5,8049,40245,20%,8049.00,Net Banking,PuneWest
778,11771,2024-04-22,2024,Apr,22,Faiyaz Saha,West,Pune,Home Decor,Wall Art,Wall Art A,5,7890,39450,20%,7890.00,COD,PuneWest
834,12156,2024-05-01,2024,May,1,Madhav Deo,West,Pune,Furniture,Table,Table Numquam,5,8417,42085,20%,8417.00,Credit Card,PuneWest
847,11346,2024-05-03,2024,May,3,Zaina Kadakia,West,Pune,Home Decor,Lamp,Lamp Veritatis,5,2782,13910,10%,1391.00,COD,PuneWest
956,14989,2024-05-19,2024,May,19,Fateh Apte,West,Pune,Toys,Board Game,Board Game Ab,5,8167,40835,20%,8167.00,UPI,PuneWest
957,10440,2024-05-20,2024,May,20,Anvi Raju,West,Pune,Sports,Dumbbells,Dumbbells Accusamus,5,9315,46575,20%,9315.00,Credit Card,PuneWest
1009,14952,2024-05-26,2024,May,26,Neysa Kota,West,Pune,Books,Comics,Comics Ea,5,7565,37825,20%,7565.00,UPI,PuneWest
1053,14757,2024-06-01,2024,Jun,1,Badal Rao,West,Pune,Groceries,Rice,Rice Optio,5,8240,41200,20%,8240.00,Debit Card,PuneWest
1116,12966,2024-06-10,2024,Jun,10,Divij Dhingra,West,Pune,Clothing,Shoes,Shoes Nihil,5,8560,42800,20%,8560.00,Credit Card,PuneWest
1179,12598,2024-06-19,2024,Jun,19,Arnav Deo,West,Pune,Beauty,Perfume,Perfume Dolor,5,8137,40685,20%,8137.00,Credit Card,PuneWest
1250,10574,2024-07-01,2024,Jul,1,Jayan Doshi,West,Pune,Kitchen,Microwave,Microwave Nam,5,7282,36410,20%,7282.00,Debit Card,PuneWest
1296,13338,2024-07-07,2024,Jul,7,Parinaaz Gandhi,West,Pune,Beauty,Perfume,Perfume Illum,5,8779,43895,20%,8779.00,Credit Card,PuneWest
1306,14168,2024-07-09,2024,Jul,9,Charvi Dua,West,Pune,Sports,Yoga Mat,Yoga Mat Dolorum,5,7642,38210,20%,7642.00,COD,PuneWest
1336,13558,2024-07-14,2024,Jul,14,Amani Shukla,West,Pune,Clothing,Men's Wear,Men's Wear Et,5,8709,43545,20%,8709.00,Debit Card,PuneWest
1378,13456,2024-07-19,2024,Jul,19,Dharmajan Gera,West,Pune,Clothing,Women's Wear,Women's Wear Repellat,5,1061,5305,5%,265.25,Net Banking,PuneWest
1391,13300,2024-07-21,2024,Jul,21,Nirvi Sankaran,West,Pune,Home Decor,Lamp,Lamp Enim,5,8835,44175,20%,8835.00,Debit Card,PuneWest
1479,14229,2024-08-02,2024,Aug,2,Kanav Vohra,West,Pune,Clothing,Kids Wear,Kids Wear Error,5,9956,49780,20%,9956.00,Credit Card,PuneWest
1724,12826,2024-09-04,2024,Sep,4,Sumer Savant,West,Pune,Kitchen,Juicer,Juicer Dicta,5,9948,49740,20%,9948.00,Net Banking,PuneWest
1805,12814,2024-09-14,2024,Sep,14,Chirag Boase,West,Pune,Beauty,Lipstick,Lipstick At,5,9370,46850,20%,9370.00,Debit Card,PuneWest
1910,11764,2024-10-01,2024,Oct,1,Mishti Halder,West,Pune,Clothing,Men's Wear,Men's Wear Incidunt,5,9101,45505,20%,9101.00,Debit Card,PuneWest
1934,13255,2024-10-04,2024,Oct,4,Gatik Singh,West,Pune,Kitchen,Refrigerator,Refrigerator Officiis,5,9961,49805,20%,9961.00,UPI,PuneWest
2020,12615,2024-10-11,2024,Oct,11,Kavya Rajan,West,Pune,Furniture,Sofa,Sofa Iure,5,9257,46285,20%,9257.00,COD,PuneWest
2209,13074,2024-10-23,2024,Oct,23,Samiha Sachar,West,Pune,Furniture,Sofa,Sofa Atque,5,7725,38625,20%,7725.00,UPI,PuneWest
2449,12286,2024-11-11,2024,Nov,11,Hridaan Shroff,West,Pune,Toys,Board Game,Board Game Blanditiis,5,8860,44300,20%,8860.00,Debit Card,PuneWest
2469,11390,2024-11-12,2024,Nov,12,Dishani Luthra,West,Pune,Home Decor,Vase,Vase Commodi,5,7710,38550,20%,7710.00,Credit Card,PuneWest
2505,10563,2024-11-16,2024,Nov,16,Shayak Lal,West,Pune,Electronics,Camera,Camera Fugiat,5,7236,36180,20%,7236.00,Debit Card,PuneWest
2570,10948,2024-11-20,2024,Nov,20,Jivika Vohra,West,Pune,Toys,RC Car,RC Car Natus,5,9599,47995,20%,9599.00,Debit Card,PuneWest
2666,11141,2024-11-27,2024,Nov,27,Anika Saxena,West,Pune,Sports,Football,Football Dolor,5,9130,45650,20%,9130.00,Net Banking,PuneWest
2907,12080,2024-12-13,2024,Dec,13,Rati Mangal,West,Pune,Home Decor,Cushion,Cushion Rem,5,9695,48475,20%,9695.00,Credit Card,PuneWest
2992,12793,2024-12-19,2024,Dec,19,Samaira Kata,West,Pune,Furniture,Bed,Bed Accusamus,5,7343,36715,20%,7343.00,UPI,PuneWest
2993,13569,2024-12-19,2024,Dec,19,Advika Dara,West,Pune,Groceries,Sugar,Sugar Ex,5,9618,48090,20%,9618.00,Debit Card,PuneWest
3095,12620,2024-12-29,2024,Dec,29,Myra Sehgal,West,Pune,Furniture,Cabinet,Cabinet Voluptatibus,5,9966,49830,20%,9966.00,Credit Card,PuneWest
3316,10063,2025-01-26,2025,Jan,26,Drishya Apte,West,Pune,Kitchen,Juicer,Juicer Totam,5,8905,44525,20%,8905.00,Debit Card,PuneWest
3356,13069,2025-02-01,2025,Feb,1,Manjari Rajagopal,West,Pune,Books,Textbook,Textbook Animi,5,8898,44490,20%,8898.00,COD,PuneWest
3787,14290,2025-04-04,2025,Apr,4,Neelofar Bhatt,West,Pune,Toys,Board Game,Board Game Repudiandae,5,8955,44775,20%,8955.00,Debit Card,PuneWest
3790,10006,2025-04-06,2025,Apr,6,Vardaniya Jayaraman,West,Pune,Furniture,Chair,Chair Assumenda,5,9083,45415,20%,9083.00,Credit Card,PuneWest
3879,14113,2025-04-17,2025,Apr,17,Riya Yohannan,West,Pune,Kitchen,Mixer Grinder,Mixer Grinder Minus,5,7036,35180,20%,7036.00,Debit Card,PuneWest
3933,10490,2025-04-25,2025,Apr,25,Nayantara Rajagopalan,West,Pune,Groceries,Oil,Oil Explicabo,5,8703,43515,20%,8703.00,UPI,PuneWest
3991,10870,2025-05-06,2025,May,6,Dishani Wali,West,Pune,Furniture,Table,Table Animi,5,7377,36885,20%,7377.00,Debit Card,PuneWest
4262,14765,2025-06-09,2025,Jun,9,Yasmin Mangal,West,Pune,Sports,Cricket Bat,Cricket Bat Quia,5,8389,41945,20%,8389.00,Net Banking,PuneWest
4432,12339,2025-07-07,2025,Jul,7,Ishaan Kalla,West,Pune,Home Decor,Wall Art,Wall Art Veniam,5,8674,43370,20%,8674.00,COD,PuneWest
4455,14331,2025-07-10,2025,Jul,10,Ritvik Verma,West,Pune,Home Decor,Clock,Clock Dignissimos,5,7511,37555,20%,7511.00,Credit Card,PuneWest
4479,14551,2025-07-13,2025,Jul,13,Riaan Lad,West,Pune,Books,Textbook,Textbook Delectus,5,7683,38415,20%,7683.00,Net Banking,PuneWest
4597,11254,2025-08-03,2025,Aug,3,Manikya Halder,West,Pune,Electronics,Headphones,Headphones Corporis,5,9356,46780,20%,9356.00,Credit Card,PuneWest
4954,10161,2025-09-26,2025,Sep,26,Myra Handa,West,Pune,Home Decor,Clock,Clock Officia,5,8527,42635,20%,8527.00,COD,PuneWest